[package]
name = "note-cli"
version = "0.1.0"
authors = ["Adrian Unger <dev@staydecent.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.9"
